name: Build APK
on:
  push:
    branches: [ "main" ]  # Триггер при пуше в ветку main
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu
    steps:
      # Шаг 1: Загружаем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Рекомендуется Python 3.10

      # Шаг 3: Устанавливаем зависимости
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
              python3-dev \
              python3-pip \
              python3-venv \
              zlib1g-dev \
              build-essential

      # Шаг 4: Устанавливаем Buildozer
      - name: Install Buildozer
        run: pip install buildozer

      # Шаг 5: Запускаем сборку APK
      - name: Build APK
        run: |
          buildozer -v android clean  # Очистка предыдущих сборок
          buildozer -v android debug  # Сборка APK

      # Шаг 6: Сохраняем APK как артефакт
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: bin/*.apk  # Путь к собранному APK
